### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by niallbarrett** [functino/buzz-buzzers#1]
Getting the following issue when I try to install on my Windows 10 machine. `npm install buzz-buzzers`:

> node-pre-gyp info check checked for "C:\Users\Niall\Desktop\buzz\node_modules\node-hid\build\HID\v0.5.1\Release\node-v57-win32-x64\HID.node" (not found)

Same error on RunKit:
[https://runkit.com/embed/fynw6hfoe196](https://runkit.com/embed/fynw6hfoe196)

> Error: Cannot find module '/app/available_modules/1511531349000/buzz-buzzers/node_modules/node-hid/build/HID/v0.5.1/Release/node-v57-linux-x64/HID.node'

Any ideas?

**Comment by functino** [comment]
Hi @niallbarrett sorry for the super late reply. I don't currently have the time to look into this issue. I'm on OS X and don't experience this problem. 
Maybe someone with Windows can debug this :(

**Comment by functino** [comment]
@CDaxi thanks for your investigation. I've updated all dependencies now. Maybe that fixes the problem...
