### ISSUE TITLE
Wireless Buzzers automatically turn off

### ISSUE THREAD

**Issue by Metasabaca** [functino/buzz-buzzers#2]
Hello,

First of all thank you very much for this package that works very well with what I'm doing. However there is a little problem with the original PS3 wireless Buzzers : they automatically turn off if left idle for about 20 minutes or so.

I suppose it's a feature that's impossible to disable, so would it be possible to prevent them from turning off by themselves by calling setLeds after 19 minutes of inactivity ?

Or is there another more aesthetic method to do it, such as a specific byte message to send via node-hid ?

**Comment by functino** [comment]
HI @Metasabaca, sorry for the late reply. 
I think flashing the LEDs every x minutes is a very reasonable approach. I'll add that once I have some spare time. Or if you'd like do a PR :)

**Comment by functino** [comment]
Hi @Metasabaca,
I had some time to work on this. Unfortunately it seems to not be possible to prevent the wireless buzzers from turning off by flashing the leds periodically. After ~20 minutes without any button pressed they turn off.
If you'd like to try yourself there is a branch with a new `keepAlive` flag: https://github.com/functino/buzz-buzzers/tree/keep-alive
